routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('', 'HomeController@welcome')->name('welcome');
Route::get('locale/{locale}', 'HomeController@locale')->name('locale');

Route::middleware('auth')->group(function () {
    Route::get('home', 'HomeController@home')->name('home');

    Route::get('settings', 'UsersController@settings')->name('settings');
    Route::post('settings', 'UsersController@password')->name('settings.password');

    Route::get('admins', 'AdminsController@index')->name('admins');
    Route::post('admins', 'AdminsController@store')->name('admins.store')->middleware('can:create,App\Models\Admin');
    Route::get('admins/new', 'AdminsController@form')->name('admins.form')->middleware('can:create,App\Models\Admin');
    Route::get('admin/{id}', 'AdminsController@show')->name('admin');

    Route::get('emails', 'EmailsController@index')->name('emails');
    Route::post('emails', 'EmailsController@send')->name('emails.send');
    Route::get('email/{id}', 'EmailsController@show')->name('email');
    Route::get('email/{id}/rendered', 'EmailsController@view')->name('email.view');

    Route::get('subscribers', 'SubscribersController@index')->name('subscribers');
    Route::post('subscribers', 'SubscribersController@subscribe')->name('subscribe');
    Route::get('subscriber/{id}', 'SubscribersController@show')->name('subscriber');
});

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Email;
use App\Models\Subscriber;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Contracts\View\Factory;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\View\View;

class HomeController extends Controller
{
    /**
     * Show Welcome page.
     *
     * @return Application|Factory|View
     */
    public function welcome()
    {
        return view('welcome');
    }

    public function locale(string $locale)
    {
        session()->put('locale', $locale);
        return redirect()->back();
    }

    /**
     * Show dashboard.
     *
     * @return Renderable
     */
    public function home()
    {
        $all_subscribers = Subscriber::select(['id', 'first_name', 'last_name'])->orderBy('first_name')->get();
        $subscribers = Subscriber::withCount('emails')->take(10)->get();
        $emails = Email::with(['receiver:id,first_name,last_name,full_name', 'sender:id,first_name,last_name'])
            ->select(['id', 'subject', 'receiver_id', 'sender_id'])->take(10)->get();

        $templates = collect(Storage::disk('views')->files('vendor/maileclipse/templates'))->filter(function ($file) {
            return !Str::contains($file, '_');
        })->map(function ($file) {
            return [
                'name' => Str::ucfirst(Str::between($file, 'templates/', '.blade')),
                'address' => Str::before($file, '.blade.php'),
            ];
        })->all();

        return view('home')
            ->with(compact('all_subscribers'))
            ->with(compact('subscribers'))
            ->with(compact('emails'))
            ->with(compact('templates'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')
@section('title')
    @lang('Dashboard')
@endsection
@section('head')
    <style>
        .list-group {
            max-height: 500px;
            overflow: auto;
        }
    </style>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">@lang('New Email')</div>
                    <div class="card-body">
                        <form method="post" action="{{ route('email.send') }}">
                            @csrf
                            <div class="form-group">
                                <label for="subject">@lang('Subject')</label>
                                <input class="form-control" id="subject" name="subject" type="text">
                            </div>
                            <div class="form-group">
                                <label for="receivers">@lang('Recipients')</label>
                                <select class="form-control" id="receivers" name="receivers[]" multiple>
                                    @foreach($all_subscribers as $subscriber)
                                        <option value="{{ $subscriber->id }}">{{ $subscriber->full_name }}</option>
                                    @endforeach
                                </select>
                                <small class="form-text text-muted">@lang('Up to 100 subscribers').</small>
                            </div>
                            <div class="form-group">
                                <label for="template">@lang('Template')</label>
                                <select class="form-control" id="template" name="template" dir="ltr">
                                    @foreach($templates as $template)
                                        <option value="{{ $template['address'] }}">{{ $template['name'] }}
                                            ({{ $template['address'] }})
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <label for="editor">@lang('Message')</label>
                            <div dir="rtl">
                                <textarea id="editor" name="message"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">@lang('Send')</button>
                        </form>
                        <div class="mt-3">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            @if(session('success'))
                                <div class="alert alert-success">
                                    <p>@lang('Has been successfully sent')!</p>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-5 justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <div>@lang('Latest Subscribers')</div>
                        <a href="{{ route('subscribers') }}" class="btn btn-primary">@lang('View All')</a>
                    </div>
                    <div class="card-body">
                        <div class="list-group">
                            @foreach($subscribers as $subscriber)
                                <a href="{{ route('subscriber', ['id' => $subscriber->id]) }}"
                                   class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                                    {{ $subscriber->full_name }}
                                    <span class="badge badge-primary badge-pill">{{ $subscriber->emails_count }}</span>
                                </a>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <div>@lang('Latest Emails')</div>
                        <a href="{{ route('emails') }}" class="btn btn-primary">@lang('View All')</a>
                    </div>
                    <div class="card-body">
                        <div class="list-group">
                            @foreach($emails as $email)
                                <a href="{{ route('email', ['id' => $email->id]) }}"
                                   class="list-group-item list-group-item-action">
                                    {{ $email->sender->full_name }}:
                                    <b>{{ $email->subject }}</b> @lang('to')
                                    <em>{{ $email->receiver->full_name }}</em>
                                    <small>({{ \Carbon\Carbon::parse($email->created_at, 'UTC')->toDateTimeString() }}
                                        )</small>
                                </a>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        const md = new SimpleMDE({
            forceSync: true,
        });
    </script>
@endsection

resources/views/settings.blade.php
@extends('layouts.app')
@section('title')
    @lang('Settings')
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">@lang('Your Information')</div>
                    <div class="card-body">
                        <div class="list-group">
                            <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                                <div>@lang('First Name')</div>
                                <b>{{ $user->first_name }}</b>
                            </a>
                            <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                                <div>@lang('Last Name')</div>
                                <b>{{ $user->last_name }}</b>
                            </a>
                            <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                                <div>@lang('Email')</div>
                                <b>{{ $user->email }}</b>
                            </a>
                            <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                                <div>@lang('Level')</div>
                                <b>{{ __(\Illuminate\Support\Str::ucfirst($user->level)) }}</b>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">@lang('Change Password')</div>
                    <div class="card-body">
                        <form method="post">
                            @csrf
                            <div class="form-group">
                                <label for="password">@lang('New Password')</label>
                                <input class="form-control" id="password" name="password" type="password">
                            </div>
                            <button type="submit" class="btn btn-primary">@lang('Submit')</button>
                        </form>
                        @if(session('success'))
                            <div class="alert alert-success mt-3">
                                <p>@lang('Has been successfully changed')!</p>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection